using TMPro;
using UnityEditor.Build.Content;
using UnityEngine;
using UnityEngine.SceneManagement;
public class GameDirector : MonoBehaviour
{
    GameObject timerText;
    GameObject pointText;
    float time=60.0f;
    public static int point=0;
    public void GetApple()
    {
        this.point+=100;
    }
    public void GetBomb()
    {
        this.point/=2;
    }
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        this.timerText=GameObject.Find("Time");
        this.pointText=GameObject.Find("Point");
    }

    // Update is called once per frame
    void Update()
    {
        this.time-=Time.deltaTime;
        this.timerText.GetComponent<TextMeshProUGUI>().text=this.time.ToString("F1");
        this.pointText.GetComponent<TextMeshProUGUI>().text=this.point.ToString()+" point";
        if(time<=0)
        {
            SceneManager.LoadScene("Result");
        }
    }
}
